name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -c "import pptx; print('python-pptx installed successfully')"
        python -c "import matplotlib; print('matplotlib installed successfully')"
        python -c "import streamlit; print('streamlit installed successfully')"

    - name: Test presentation generation
      run: |
        python generate_presentation.py
        python generate_visualizations.py
        ls -la *.pptx *.png

  build-mcp-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Node.js dependencies
      run: |
        cd seminar-generator
        npm install

    - name: Build MCP server
      run: |
        cd seminar-generator
        npm run build

    - name: Test MCP server
      run: |
        cd seminar-generator
        node build/index.js --help || echo "Server built successfully"

  deploy:
    needs: [test, build-mcp-server]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add deployment commands here
        echo "Deployment completed"
